import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import AddGrocerry from "@/Components/AddGrocerry";
import ShowGrocerry from "@/Components/ShowGrocerry";
import Container from "@mui/material/Container";
import { toast } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Grocery List</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<Container>
						<ShowGrocerry />
						<AddGrocerry />
					</Container>
				</div>
			</main>
		</>
	);
}
